config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/restaurants/cuisine/:type' => 'restaurants#index'
  post '/restaurants/search' => 'restaurants#search'

  delete '/signout' => 'sessions#destroy'
  resources :cities, only: [:index]
  resources :cities, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:index, :show, :new, :create]

  resources :chefs, only: [:index, :new, :create, :show, :edit, :update]
  resources :chefs, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:show] do
    resources :comments, only: [:new, :create, :show, :index]
  end
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many :comments
  has_many :restaurants, through: :comments

  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
  has_secure_password

  def unrecommended_restaurants
    (Restaurant.all.map{|r| r.id} - self.restaurant_ids).map{|id| Restaurant.find(id)}
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :find_chef, only: [:show, :edit, :update]

  #GET /chefs/new (show signup form)
  def new
    @chef = Chef.new
    render 'chefs/new', :layout => false
  end

  #POST /chefs (create new chef user)
  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      session[:email] = @chef.email
      redirect_to root_path
    else
      render :new, :layout => false
    end

  end

  #GET /chefs/:id
  def show
  end

  def edit
    if @chef.email != session[:email]
      redirect_to chef_path(current_user)
    end
  end

  def update
    @chef.update(chef_params)
    redirect_to chef_path(@chef)
  end

  private

  def chef_params
    params.require(:chef).permit(:name, :email, :password, :uid, :hometown, :employer)
  end

  def find_chef
    @chef = Chef.find(params[:id])
  end
end

app/views/chefs/_form.html.erb
<%= stylesheet_link_tag    'application' %>

<div class="form">
    <%= f.label :name, :class => "required" %>
    <%= f.text_field :name, placeholder: @chef.errors[:name] ? @chef.errors[:name][0] : 'Name', :class => "input-field" %><br>
    <%= f.label :email, :class => "required" %>
    <%= f.text_field :email, placeholder: @chef.errors[:email] ? @chef.errors[:email][0] : 'Email', :class => "input-field" %><br>
    <%= f.label :password, :class => "required" %>
    <%= f.password_field :password, placeholder: @chef.errors[:password] ? @chef.errors[:password][0] : 'Password', required: true, :class => "input-field" %><br>
    <%= f.label :hometown %>
    <%= f.text_field :hometown, :class => "input-field" %><br>
    <%= f.label :employer %>
    <%= f.text_field :employer, :class => "input-field" %><br>
</div>

app/views/chefs/edit.html.erb
<!-- form to be rendered when chef edits account info -->
<h1>Edit your Eats Abroad profile</h1>
<%= form_for(@chef) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Update Account Info", class: ["button"] %>
<% end %>

app/views/chefs/new.html.erb
<%= stylesheet_link_tag    'application' %>
<!-- form to be rendered when chef signs up for new account -->
<div class="center">
  <img class="logo" src="/Eats Abroad Logo-v-5A Mar.jpg" width="165" height="125" alt="Eats Abroad logo">
  <h2>Sign up for a new Eats Abroad account</h2>
</div>
  <%= form_for @chef, url: chefs_path, method: :post do |f| %>
    <%= render 'form', f: f %>
    <div class="create-account">
      <%= f.submit "Create Account", class: ["button"] %>
    </div>
  <% end %>

app/views/chefs/show.html.erb
<%= stylesheet_link_tag    'application' %>

<div class="profile">
  <div class="profile-heading">
    <h1><%= @chef.name %>'s Profile</h1>
  </div>
  <div class="profile-info">
    <p><strong>Hometown:</strong> <%= @chef.hometown %></p>
    <p><strong>My Restaurants:</strong> <%= @chef.employer %></p>
    <p><strong>My Recommendations:</strong> </p>
    <ul>
      <% @chef.restaurants.uniq.each do |restaurant| %>
        <li><%= link_to restaurant.name, restaurant_path(restaurant) %><br></li>
      <% end %>
    </ul>
    <!-- edit profile if you're the chef -->
    <% if params[:id] == current_user.id.to_s %>
      <%= link_to "Edit my profile", edit_chef_path(@chef) %>
    <% end %>
  </div>
  </div>