config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/restaurants/cuisine/:type' => 'restaurants#index'
  post '/restaurants/search' => 'restaurants#search'

  delete '/signout' => 'sessions#destroy'
  resources :cities, only: [:index]
  resources :cities, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:index, :show, :new, :create]

  resources :chefs, only: [:index, :new, :create, :show, :edit, :update]
  resources :chefs, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:show] do
    resources :comments, only: [:new, :create, :show, :index]
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :city
  has_many :comments
  has_many :chefs, through: :comments

  validates :name, presence: true
  validates :city_id, presence: true

  before_validation :capitalize_cuisine

  def self.by_cuisine(cuisine)
    self.where(cuisine: cuisine.capitalize)
  end

  def capitalize_cuisine
    self.cuisine = self.cuisine.titleize
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login

  #GET /restaurants (account for nested route and plain /restaurants route)
  def index
    if params[:type]
      #find restaurants with this cuisine type
      @restaurants = Restaurant.by_cuisine(params[:type])
    elsif params[:city_id]
      @city = City.find(params[:city_id])
      @restaurants = @city.restaurants
    elsif params[:chef_id]
      @chef = Chef.find(params[:chef_id])
      @restaurants = @chef.restaurants
      respond_to do |f|
        f.html
        f.json {render json: @restaurants}
      end
    else
      @restaurants = Restaurant.all
      respond_to do |f|
        f.html
        f.json {render json: @restaurants}
      end
    end
  end

  #GET /restaurants/:id
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |f|
      f.html
      f.json {render json: @restaurant}
    end
  end

  def search
    redirect_to "/restaurants/cuisine/#{params[:search]}"
  end

  #GET /restaurants/new
  def new
    @chef = current_user
    @restaurant = Restaurant.new
  end

  #POST
  def create
    @chef = current_user
    @restaurant = Restaurant.new

    #to handle existing restaurant addition
    if params[:restaurant][:id] #will have id from dropdown
      if params[:restaurant][:id] != ""
        @restaurant = Restaurant.find(params[:restaurant][:id]) #find the restaurant instance
        redirect_to new_restaurant_comment_path(@restaurant) #go to that restaurant's comments page
      else
        render :new
      end
    # elsif !params[:restaurant][:id]
    #   render :new
    #to handle brand new restaurant addition
    elsif params[:restaurant][:name] != "" && params[:restaurant][:city_id] != ""
      #if name and city ID are provided (required per validations)
      if Restaurant.find_by(:name => params[:restaurant][:name]) # if name matches existing an restaurant
        @restaurant = Restaurant.find_by(:name => params[:restaurant][:name]) #find the instance, assign to @restaurant
        redirect_to new_restaurant_comment_path(@restaurant) #go to new comment page
      else  #if it's a brand new restaurant not in the database
        if params[:restaurant][:cuisine] == ""
          params[:restaurant][:cuisine] = "Cuisine not specified"
        end
        @new_restaurant = current_user.restaurants.build(restaurant_params)
        if @new_restaurant.save # .valid would simply check and not save, but then I don't have a restaurant ID for the comments...
          respond_to do |format|
            format.html {redirect_to new_restaurant_comment_path(@new_restaurant)} #go to that restaurant's comments page
            format.js { }
          end
          #redirect_to new_restaurant_comment_path(@new_restaurant)
        else
          render :new
        end
      end
      #to handle a brand new restaurant addition with missing required fields
    elsif params[:restaurant][:name] == "" || params[:restaurant][:city_id] == ""
      @restaurant = Restaurant.new(restaurant_params) #this won't save because it's missing a required field
      if !@restaurant.save
        render :new
      end
    end
  end

private

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine, :city_id)
  end

  def require_login
    return head(:forbidden) unless session.include? :email
  end

  def add_default_cuisine
    @restaurant.cuisine = "Cuisine not specified"
  end

end

app/views/restaurants/_iterate.html.erb
<ul>
  <% @restaurants.each do |r| %>
    <li><%= link_to r.name, restaurant_path(r) %></li>
  <% end %>
</ul>

app/views/restaurants/create.js.erb
let commentFormHtml = "<h2>Enter a comment for <%= @new_restaurant.name %>:</h2><form action='/restaurants/<%= @new_restaurant.id %>/comments' method='post' accept-charset='UTF-8'><label>Your thoughts:</label></form><input type='text' name='comment[content]' id='comment_content'><input type='submit' name='commit' value='Add Comment' data-disable-with='Add Comment'>"
//debugger
$('#body-container').after(commentFormHtml)

app/views/restaurants/index.html.erb
<% if current_user.id.to_s == params[:chef_id] %>
  <h1>My Recommended Restaurants</h1>
  <% if @restaurants.size == 0 %>
    <p>You haven't recommended any restaurants yet! Click <%= link_to "here", new_restaurant_path %> to get started.</p>
  <% else %>
    <%= render 'iterate' %>
    <br>
    <%= link_to "Recommend a new restaurant", new_restaurant_path %>
  <% end %>
<% elsif params[:chef_id] %>
  <h1><%= @chef.name %>'s Recommended Restaurants</h1>
    <%= render 'iterate' %>
<% elsif params[:city_id] %>
  <h1>Recommended Restaurants in <%= @city.name %></h1>
    <%= render 'iterate' %>
<% elsif params[:type] %>
  <h1>Recommended <%= params[:type].capitalize %> Restaurants on Eats Abroad</h1>
    <%= render 'iterate' %>
<% else %>
  <h1>Recommended Restaurants on Eats Abroad</h1>
    <%= render 'iterate' %>
<% end %>

<h2>Search by Cuisine</h2>
<%= form_tag restaurants_search_path do %>
  <label>Search</label>
  <%= text_field_tag :search %>
  <%= submit_tag "Search"%>
<% end %>

app/views/restaurants/new.html.erb
<%= stylesheet_link_tag    'application' %>

<div class="row">
  <div class="center column">
    <h2>Add an existing restaurant to your recommendations:</h2>
    <%= form_for :restaurant, :url => url_for(:controller => 'restaurants', :action => 'create'), :html => {:id => "add_existing"}, method: :post do |f| %>
      <%= f.collection_select :id, @chef.unrecommended_restaurants, :id, :name, :prompt => "Please select" %>
      <%= f.submit "Add to My List", :class => "button" %>
    <% end %>
  </div>

  <div class="center column">
    <h2>Or add a new restaurant to your recommendations:</h2>
    <div class="form">
    <%= form_for @restaurant do |f| %>
      <%= f.label :name, :class => "required" %>
      <%= f.text_field :name, placeholder: @restaurant.errors[:name] ? @restaurant.errors[:name][0] : '' %><br>
      <%= f.label :cuisine %>
      <%= f.text_field :cuisine %><br>
      <%= f.label :city, :class => "required" %>
      <%= f.collection_select :city_id, City.all, :id, :name, :prompt => "Please select" %><br>
      <% if @restaurant.errors[:city_id] != [] %>
        <div class="field_with_errors"><%= @restaurant.errors[:city_id][0] %></div>
      <% end %>
      <%= f.submit "Create Restaurant and Add to My List", :class => "button" %>
    <% end %>
  </div>
</div>

app/views/restaurants/search.html.erb
<h2>Search by Cuisine</h2>
<%= form_tag(restaurants_search_new_path method: :get) do %>
  <label>Search</label>
  <%= text_field_tag :search %>
  <%= submit_tag "Search"%>
<% end %>

app/views/restaurants/show.html.erb
<%= stylesheet_link_tag    'application' %>

<div class="profile">
  <div class="profile-heading">
    <h1><%= @restaurant.name %></h1>
  </div>
  <div class="profile-info">
    <h3>Cuisine: <%= @restaurant.cuisine %></h3>

    <h3>Recommendations:</h3>
    <ul>
      <% @restaurant.comments.each do |c| %>
        <li><%= c.content %> - <%= link_to c.chef.name, chef_path(c.chef) %></li>
      <% end %>
    </ul>
  </div>
</div>