config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#home'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create'
  get '/restaurants/cuisine/:type' => 'restaurants#index'
  post '/restaurants/search' => 'restaurants#search'

  delete '/signout' => 'sessions#destroy'
  resources :cities, only: [:index]
  resources :cities, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:index, :show, :new, :create]

  resources :chefs, only: [:index, :new, :create, :show, :edit, :update]
  resources :chefs, only: [:show] do
    resources :restaurants, only: [:index, :show]
  end

  resources :restaurants, only: [:show] do
    resources :comments, only: [:new, :create, :show, :index]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def home
    @chef = Chef.find_by(:email => session[:email])
    if !@chef
      render :layout => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= Chef.find_by(:email => session[:email])
  end

  def logged_in?
    @current_user != nil
  end
end

app/views/application/home.html.erb
<%= stylesheet_link_tag    'application' %>

<% if session[:email] %>
<div class="center">
  <h1>Welcome, <%= @chef.name %>!</h1>
  <p><%= link_to "View my recommended restaurants", chef_restaurants_path(@chef), :class => "restaurant_index" %></p>
</div>
  <!-- <p><%= link_to "View my profile", chef_path(@chef) %></p> -->
  <!-- <p><%= link_to "Log Out", signout_path, method: :delete %></p> -->
<% else %>
  <div class="center">
    <img class="logo" src="/Eats Abroad Logo-v-5A Mar.jpg" width="165" height="125" alt="Eats Abroad logo">
    <h1>Welcome!</h1>
    <p>Please <%= link_to "sign in", signin_path %> or <%= link_to "create an account", new_chef_path %></p>
  </div>
<% end %>